# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sergi/TESTSsc/TESTSsc.cache/wt [current_project]
set_property parent.project_path C:/Users/sergi/TESTSsc/TESTSsc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/sergi/TESTSsc/TESTSsc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/scs.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/efsfsrf.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/xsdea.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/fsfses.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/SSD.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/debouncer.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/fdsfrsfs.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/grsdfsfes.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/sfesfes.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/fsfs.vhd
  C:/Users/sergi/TESTSsc/TESTSsc.srcs/sources_1/new/Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sergi/TESTSsc/TESTSsc.srcs/constrs_1/new/constrangeri.xdc
set_property used_in_implementation false [get_files C:/Users/sergi/TESTSsc/TESTSsc.srcs/constrs_1/new/constrangeri.xdc]


synth_design -top Main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
